name: Dockerize and push to GHCR

on:
  push:
    branches:
      - main

jobs:
  Dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/ct_webapp:latest
            ghcr.io/${{ env.IMAGE_OWNER }}/ct_webapp:${{ github.sha }}
